import Head from "next/head";
import styles from "@/styles/Home.module.css";
import ItemCard from "@/components/ItemCard";
import AddToCartButton from "@/components/AddToCartButton";

export default function Home() {
  return (
    <>
      <Head>
        <title>Rental Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
